common:
containerRegistryUrl: avishekacr.azurecr.io
ingressClass : azure-application-gateway

Ui:
  replicas: 2
  image : 
    name : todo-ui
    tag : v1
  port : 80
  Serviceport : 80
  ingress: 
    Host : dev-ui.pagla.shop

getTask:
  replicas: 2
  image:
    name: todo-get-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-dev-todoapp-78666.database.windows.net,1433;Database=sqldb-dev-todoapp;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: dev-get-tasks-api.pagla.shop
    ingressClass: azure-application-gateway

deleteTask:
  replicas: 2
  image:
    name: todo-delete-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-dev-todoapp-78666.database.windows.net,1433;Database=sqldb-dev-todoapp;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: dev-delete-task-api.jhandu.shop
    ingressClass: azure-application-gateway


addTask:
  replicas: 2
  image:
    name: todo-add-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-dev-todoapp-78666.database.windows.net,1433;Database=sqldb-dev-todoapp;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: dev-add-task-api.jhandu.shop
    ingressClass: azure-application-gateway