apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{. Release.Name}}-todo-ui
spec:
  replicas: {{. Release.Value}}
  selector:
    matchLabels:
      app: {{. Release.Name}}-todo-ui
  template:
    metadata:
      labels:
        app: {{. Release.Name}}-todo-ui
    spec:
      containers:
      - name: {{. Release.Name}}-todo-ui
        image: "{{. Values.common.ccontainerRegistryUrl}}/{{.Values.Ui.image.name}}/{{. Values.Ui.image.tag}}"
        ports:
        - containerPort: 80
