apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{. Release.Name}}-todo-ui-ingress
spec:
  ingressClassName: {{. Value.common.ingressClass }}
  rules:
  - host: {{ . Values.Ui.ingress.Host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ . Release.Name }}-todo-ui-svc
            port: 
              number: {{ .Value.Ui.port }}
